// generated by generator/samples.py - do not edit
#ifndef MINICHORD_SAMPLES_H
#define MINICHORD_SAMPLES_H
#include <Audio.h>

// The sampled instruments, in voice source order (harp voice and chord voice 1-4)
extern const AudioSynthWavetable::instrument_data piano_instrument;   // piano (FluidR3)
extern const AudioSynthWavetable::instrument_data pizzicato_instrument;   // pizzicato strings (Musyng Kite, FluidR3 in the middle)
extern const AudioSynthWavetable::instrument_data choir_instrument;   // choir aah (Musyng Kite)
extern const AudioSynthWavetable::instrument_data strings_instrument;   // string quartet (Musyng Kite): cello, viola, violin

#endif
