#ifndef PARAMETER_LOOKUP_H
#define PARAMETER_LOOKUP_H

// Generated by generator/generate.py - do not edit by hand

#include <stdint.h>

struct ParameterInfo {
    uint8_t sysex_adress;
    bool is_selector;   // mapped across min..max; everything else scales around its value
    int16_t min_value;
    int16_t max_value;
};

static const ParameterInfo parameter_lookup[] = {
    { 20, 0, 0, 360 }, // bank color
    { 32, 0, 0, 1 }, // led attenuation
    { 21, 1, 0, 1 }, // retrigger chords
    { 22, 1, 0, 1 }, // change held strings
    { 23, 1, 0, 2 }, // slash level
    { 113, 1, 0, 4 }, // slash voice
    { 114, 1, 0, 1 }, // slash re-voice
    { 115, 1, 0, 5 }, // cantus
    { 30, 1, 0, 12 }, // transpose
    { 106, 1, 1, 16 }, // chord channel
    { 107, 1, 1, 16 }, // harp channel
    { 108, 1, 0, 1 }, // single port mode
    { 110, 1, 0, 1 }, // MPE output
    { 31, 1, 0, 1 }, // sharp function
    { 33, 1, 0, 1 }, // barry harris mode
    { 34, 1, 0, 6 }, // chord frame shift
    { 237, 1, 0, 11 }, // temperament
    { 35, 1, 0, 20 }, // chord key signature
    { 37, 1, 0, 3 }, // chord inversion
    { 38, 1, 0, 4 }, // chord spacing
    { 111, 1, 0, 2 }, // voice leading
    { 112, 1, 0, 24 }, // voice leading range
    { 109, 0, 4320, 4460 }, // master tuning
    { 39, 1, 0, 1 }, // chord layout
    { 202, 1, 0, 29 }, // alt layout maj
    { 203, 1, 0, 29 }, // alt layout min
    { 204, 1, 0, 29 }, // alt layout 7th
    { 205, 1, 0, 29 }, // alt layout maj+7th
    { 206, 1, 0, 29 }, // alt layout min+7th
    { 207, 1, 0, 29 }, // alt layout maj+min
    { 208, 1, 0, 29 }, // alt layout all three
    { 200, 0, 0, 219 }, // double tap control
    { 201, 0, 0, 4095 }, // double tap value
    { 36, 1, 0, 11 }, // scalar harp mode
    { 236, 0, 0, 4095 }, // custom scale
    { 24, 0, 0, 1 }, // reverb size
    { 25, 0, 0, 1 }, // reverb high damping
    { 26, 0, 0, 1 }, // reverb low damping
    { 27, 0, 0, 1 }, // reverb low pass
    { 28, 0, 0, 1 }, // reverb diffusion
    { 29, 0, 0, 1 }, // pan
    { 10, 0, 21, 219 }, // chord alternate control
    { 11, 0, 0, 100 }, // chord alternate range
    { 12, 0, 21, 219 }, // harp alternate control
    { 13, 0, 0, 100 }, // harp alternate percent range
    { 14, 0, 21, 219 }, // mod main control
    { 15, 0, 0, 100 }, // mod main percent range
    { 16, 0, 21, 219 }, // mod alternate control
    { 17, 0, 0, 100 }, // mod alternate percent range 
    { 4, 0, 0, 1024 }, // chord alternate value
    { 5, 0, 0, 1024 }, // harp alternate value
    { 6, 0, 0, 1024 }, // mod alternate value
    { 7, 0, 0, 10 }, // firmware revision
    { 2, 0, 0, 1 }, // global gain
    { 99, 1, 0, 4 }, // octave change
    { 40, 1, 0, 6 }, // harp shuffling
    { 98, 1, 0, 1 }, // chromatic mode
    { 41, 0, 0, 1 }, // amplitude
    { 42, 1, 0, 11 }, // waveform
    { 43, 0, 0, 5000 }, // attack
    { 44, 0, 0, 5000 }, // hold
    { 45, 0, 0, 5000 }, // decay
    { 46, 0, 0, 1 }, // sustain
    { 47, 0, 0, 5000 }, // release
    { 48, 1, 0, 10 }, // retrigger release
    { 49, 0, 0, 2000 }, // base frequency
    { 50, 0, 0, 3 }, // keytrack value
    { 51, 0, 1, 5 }, // resonance
    { 52, 0, 0, 5000 }, // attack
    { 53, 0, 0, 5000 }, // hold
    { 54, 0, 0, 5000 }, // decay
    { 55, 0, 0, 1 }, // sustain
    { 56, 0, 0, 5000 }, // release
    { 57, 0, 0, 100 }, // retrigger release
    { 58, 0, 0, 5 }, // filter sensitivity
    { 100, 1, 0, 11 }, // waveform
    { 101, 0, 0, 1 }, // amplitude
    { 102, 0, 0, 5000 }, // attack
    { 103, 0, 0, 5000 }, // hold
    { 104, 0, 0, 5000 }, // decay
    { 105, 1, 0, 24 }, // note level
    { 59, 1, 0, 11 }, // waveform
    { 60, 0, 0, 20 }, // frequency
    { 61, 0, 0, 1 }, // amplitude
    { 62, 1, 0, 11 }, // waveform
    { 63, 0, 0, 20 }, // frequency
    { 64, 0, 0, 1 }, // amplitude
    { 65, 0, 0, 5000 }, // attack
    { 66, 0, 0, 5000 }, // hold
    { 67, 0, 0, 5000 }, // decay
    { 68, 0, 0, 1 }, // sustain
    { 69, 0, 0, 5000 }, // release
    { 70, 0, 0, 100 }, // retrigger release
    { 71, 0, 0, 2 }, // pitch bend
    { 72, 0, 0, 5000 }, // attack bend
    { 73, 0, 0, 5000 }, // hold bend
    { 74, 0, 0, 5000 }, // decay bend
    { 75, 0, 0, 5000 }, // retrigger release bend
    { 76, 0, 0, 1 }, // intensity
    { 77, 0, 0, 600 }, // delay length
    { 78, 0, 0, 5000 }, // delay filter frequency
    { 79, 0, 1, 5 }, // delay filter resonance
    { 80, 0, 0, 1 }, // delay lowpass
    { 81, 0, 0, 1 }, // delay bandpass
    { 82, 0, 0, 1 }, // delay highpass
    { 83, 0, 0, 1 }, // dry mix
    { 84, 0, 0, 1 }, // delay mix
    { 85, 0, 0, 1 }, // reverb level
    { 86, 0, 0, 1 }, // crunch level
    { 87, 1, 0, 2 }, // crunch type
    { 88, 0, 0, 5000 }, // frequency
    { 89, 0, 1, 5 }, // resonance
    { 90, 0, 0, 1 }, // lowpass
    { 91, 0, 0, 1 }, // bandpass
    { 92, 0, 0, 1 }, // highpass
    { 93, 1, 0, 11 }, // LFO waveform
    { 94, 0, 0, 20 }, // LFO frequency
    { 95, 0, 0, 1 }, // LFO amplitude
    { 96, 0, 0, 5 }, // filter LFO sensitivity
    { 97, 0, 0, 2 }, // output amplifier
    { 3, 0, 0, 1 }, // global gain
    { 120, 1, 0, 5 }, // chord shuffling
    { 198, 1, 0, 4 }, // octave change
    { 199, 0, 0, 1500 }, // glide chords
    { 121, 0, 0, 1 }, // amplitude 1
    { 122, 1, 0, 11 }, // waveform 1
    { 123, 0, 0, 2 }, // frequency multiplier 1
    { 124, 0, 0, 1 }, // amplitude 2
    { 125, 1, 0, 11 }, // waveform 2
    { 126, 0, 0, 2 }, // frequency multiplier 2
    { 127, 0, 0, 1 }, // amplitude 3
    { 128, 1, 0, 11 }, // waveform 3
    { 129, 0, 0, 2 }, // frequency multiplier 3
    { 130, 0, 0, 1 }, // noise
    { 131, 0, 0, 1 }, // first note
    { 132, 0, 0, 1 }, // second note
    { 133, 0, 0, 1 }, // third note
    { 134, 0, 0, 1 }, // fourth note
    { 135, 0, 0, 100 }, // inter-note delay
    { 136, 0, 0, 100 }, // random note delay
    { 137, 0, 0, 5000 }, // attack
    { 138, 0, 0, 5000 }, // hold
    { 139, 0, 0, 5000 }, // decay
    { 140, 0, 0, 1 }, // sustain
    { 141, 0, 0, 5000 }, // release
    { 142, 0, 0, 100 }, // retrigger release
    { 143, 0, 0, 5000 }, // base frequency
    { 144, 0, 0, 1 }, // keytrack value
    { 145, 0, 1, 5 }, // resonance
    { 146, 0, 0, 5000 }, // attack
    { 147, 0, 0, 5000 }, // hold
    { 148, 0, 0, 5000 }, // decay
    { 149, 0, 0, 1 }, // sustain
    { 150, 0, 0, 5000 }, // release
    { 151, 0, 0, 100 }, // retrigger release
    { 152, 1, 0, 11 }, // LFO waveform
    { 153, 0, 0, 20 }, // LFO frequency
    { 154, 0, 0, 1 }, // LFO amplitude
    { 155, 0, 0, 5 }, // filter sensitivity
    { 156, 1, 0, 11 }, // waveform
    { 157, 0, 0, 20 }, // frequency
    { 158, 0, 0, 5 }, // keytrack value
    { 159, 0, 0, 1 }, // amplitude
    { 160, 1, 0, 11 }, // waveform
    { 161, 0, 0, 20 }, // frequency
    { 162, 0, 0, 1 }, // keytrack value
    { 163, 0, 0, 1 }, // amplitude
    { 164, 0, 0, 5000 }, // attack
    { 165, 0, 0, 5000 }, // hold
    { 166, 0, 0, 5000 }, // decay
    { 167, 0, 0, 1 }, // sustain
    { 168, 0, 0, 5000 }, // release
    { 169, 0, 0, 100 }, // retrigger release
    { 170, 0, 0, 2 }, // pitch bend
    { 171, 0, 0, 5000 }, // attack bend 
    { 172, 0, 0, 5000 }, // hold bend
    { 173, 0, 0, 5000 }, // decay bend
    { 174, 0, 0, 100 }, // retrigger release bend
    { 175, 0, 0, 1 }, // intensity
    { 176, 0, 0, 600 }, // delay length
    { 177, 0, 0, 5000 }, // delay filter frequency
    { 178, 0, 1, 5 }, // delay filter resonance
    { 179, 0, 0, 1 }, // delay lowpass
    { 180, 0, 0, 1 }, // delay bandpass
    { 181, 0, 0, 1 }, // delay highpass
    { 182, 0, 0, 1 }, // dry mix
    { 183, 0, 0, 1 }, // delay mix
    { 184, 0, 0, 1 }, // reverb level
    { 185, 0, 0, 1 }, // crunch level
    { 186, 1, 0, 2 }, // crunch type
    { 187, 0, 30, 300 }, // default_bpm
    { 188, 1, 1, 16 }, // cycle length
    { 189, 1, 1, 8 }, // measure update
    { 190, 0, 0, 2 }, // shuffle value
    { 191, 0, 20, 1000 }, // note pushed duration
    { 220, 0, 0, 128 }, // rythm pattern
    { 221, 0, 0, 128 }, // rythm pattern
    { 222, 0, 0, 128 }, // rythm pattern
    { 223, 0, 0, 128 }, // rythm pattern
    { 224, 0, 0, 128 }, // rythm pattern
    { 225, 0, 0, 128 }, // rythm pattern
    { 226, 0, 0, 128 }, // rythm pattern
    { 227, 0, 0, 128 }, // rythm pattern
    { 228, 0, 0, 128 }, // rythm pattern
    { 229, 0, 0, 128 }, // rythm pattern
    { 230, 0, 0, 128 }, // rythm pattern
    { 231, 0, 0, 128 }, // rythm pattern
    { 232, 0, 0, 128 }, // rythm pattern
    { 233, 0, 0, 128 }, // rythm pattern
    { 234, 0, 0, 128 }, // rythm pattern
    { 235, 0, 0, 128 }, // rythm pattern
    { 192, 0, 0, 5000 }, // frequency
    { 193, 0, 1, 5 }, // resonance
    { 194, 0, 0, 1 }, // lowpass
    { 195, 0, 0, 1 }, // bandpass
    { 196, 0, 0, 1 }, // highpass
    { 197, 0, 0, 2 }, // output amplifier
};

#endif // PARAMETER_LOOKUP_H
