#ifndef PARAMETER_LOOKUP_H
#define PARAMETER_LOOKUP_H

// Generated by generator/generate.py - do not edit by hand

#include <stdint.h>

struct ParameterInfo {
    uint16_t sysex_adress;
    bool is_selector;   // mapped across min..max; everything else scales around its value, within them
    int16_t min_value;  // as stored: floats in hundredths
    int16_t max_value;
};

static const ParameterInfo parameter_lookup[] = {
    { 20, 0, 0, 360 }, // bank color
    { 32, 0, 0, 100 }, // led attenuation
    { 244, 1, 0, 2 }, // usb audio
    { 243, 1, 0, 3 }, // harp plate
    { 241, 0, 0, 120 }, // harp touch threshold
    { 242, 0, 0, 119 }, // harp release threshold
    { 35, 1, 0, 20 }, // chord key signature
    { 31, 1, 0, 1 }, // sharp function
    { 30, 1, 0, 12 }, // transpose
    { 237, 1, 0, 12 }, // temperament
    { 109, 0, 4320, 4460 }, // master tuning
    { 106, 1, 1, 16 }, // chord channel
    { 107, 1, 1, 16 }, // harp channel
    { 108, 1, 0, 1 }, // single port mode
    { 110, 1, 0, 1 }, // MPE output
    { 215, 1, 0, 1 }, // harp note-off on lift
    { 8, 1, 0, 1 }, // MIDI in plays
    { 238, 1, 0, 1 }, // knobs send MIDI
    { 24, 0, 0, 100 }, // reverb size
    { 25, 0, 0, 100 }, // reverb high damping
    { 26, 0, 0, 100 }, // reverb low damping
    { 27, 0, 0, 100 }, // reverb low pass
    { 28, 0, 0, 100 }, // reverb diffusion
    { 257, 0, 0, 100 }, // string spread
    { 258, 1, 0, 1 }, // spread pattern
    { 259, 0, 0, 100 }, // chord ensemble
    { 260, 0, 0, 100 }, // vocoder
    { 261, 1, 0, 2 }, // vocoder carrier
    { 262, 0, 0, 100 }, // vocoder consonants
    { 266, 1, 0, 3 }, // MIDI clock out
    { 283, 1, 0, 4 }, // looper quantize
    { 284, 1, 0, 2 }, // looper count-in
    { 285, 1, 0, 3 }, // looper click
    { 286, 0, 0, 100 }, // looper click level
    { 288, 1, 0, 16 }, // looper length
    { 287, 1, 0, 5 }, // chord memory
    { 29, 0, 0, 100 }, // pan
    { 200, 0, 0, 511 }, // double tap control
    { 201, 0, 0, 4095 }, // double tap value
    { 209, 0, 0, 511 }, // double tap control 2
    { 210, 0, 0, 4095 }, // double tap value 2
    { 211, 0, 0, 511 }, // double tap control 3
    { 212, 0, 0, 4095 }, // double tap value 3
    { 10, 0, 21, 511 }, // chord alternate control
    { 11, 0, 0, 100 }, // chord alternate range
    { 12, 0, 21, 511 }, // harp alternate control
    { 13, 0, 0, 100 }, // harp alternate percent range
    { 14, 0, 21, 511 }, // mod main control
    { 15, 0, 0, 100 }, // mod main percent range
    { 16, 0, 21, 511 }, // mod alternate control
    { 17, 0, 0, 100 }, // mod alternate percent range 
    { 117, 1, 0, 1 }, // knob layer
    { 249, 0, 0, 511 }, // hover control
    { 250, 0, 0, 4095 }, // hover value
    { 251, 1, 3, 10 }, // hover reach
    { 256, 1, 0, 7 }, // looper
    { 4, 0, 0, 1024 }, // chord alternate value
    { 5, 0, 0, 1024 }, // harp alternate value
    { 6, 0, 0, 1024 }, // mod alternate value
    { 7, 0, 0, 1000 }, // firmware revision
    { 2, 0, 0, 100 }, // global gain
    { 36, 1, 0, 13 }, // scalar harp mode
    { 236, 0, 0, 4095 }, // custom scale
    { 267, 1, 1, 30 }, // generator
    { 268, 1, 1, 31 }, // generator notes
    { 269, 1, 0, 30 }, // generator mode
    { 98, 1, 0, 1 }, // chromatic mode
    { 116, 1, 1, 3 }, // harp rank
    { 245, 1, 0, 1 }, // harp ribbon
    { 246, 1, 0, 24 }, // ribbon span
    { 247, 0, 0, 100 }, // ribbon snap
    { 248, 0, 0, 250 }, // ribbon glide
    { 40, 1, 0, 6 }, // harp shuffling
    { 99, 1, 0, 4 }, // octave change
    { 22, 1, 0, 1 }, // change held strings
    { 41, 0, 0, 100 }, // amplitude
    { 217, 0, 0, 100 }, // string model
    { 264, 1, 0, 4 }, // harp voice
    { 218, 0, 10, 2000 }, // string decay
    { 219, 0, 0, 100 }, // string damping
    { 42, 1, 0, 11 }, // waveform
    { 43, 0, 0, 5000 }, // attack
    { 44, 0, 0, 5000 }, // hold
    { 45, 0, 0, 5000 }, // decay
    { 46, 0, 0, 100 }, // sustain
    { 47, 0, 0, 5000 }, // release
    { 48, 1, 0, 10 }, // retrigger release
    { 213, 1, 0, 12 }, // palm mute
    { 214, 0, 1, 250 }, // palm mute release
    { 216, 1, 0, 1 }, // pluck on lift
    { 252, 0, 0, 100 }, // touch velocity
    { 253, 1, 0, 2 }, // touch pressure
    { 263, 0, 0, 100 }, // strum velocity
    { 49, 0, 0, 2000 }, // base frequency
    { 50, 0, 0, 300 }, // keytrack value
    { 51, 0, 70, 500 }, // resonance
    { 52, 0, 0, 5000 }, // attack
    { 53, 0, 0, 5000 }, // hold
    { 54, 0, 0, 5000 }, // decay
    { 55, 0, 0, 100 }, // sustain
    { 56, 0, 0, 5000 }, // release
    { 57, 0, 0, 100 }, // retrigger release
    { 58, 0, 0, 500 }, // filter sensitivity
    { 100, 1, 0, 11 }, // waveform
    { 101, 0, 0, 100 }, // amplitude
    { 102, 0, 0, 5000 }, // attack
    { 103, 0, 0, 5000 }, // hold
    { 104, 0, 0, 5000 }, // decay
    { 105, 1, 0, 24 }, // note level
    { 59, 1, 0, 11 }, // waveform
    { 60, 0, 0, 2000 }, // frequency
    { 61, 0, 0, 100 }, // amplitude
    { 62, 1, 0, 11 }, // waveform
    { 63, 0, 0, 2000 }, // frequency
    { 64, 0, 0, 100 }, // amplitude
    { 65, 0, 0, 5000 }, // attack
    { 66, 0, 0, 5000 }, // hold
    { 67, 0, 0, 5000 }, // decay
    { 68, 0, 0, 100 }, // sustain
    { 69, 0, 0, 5000 }, // release
    { 70, 0, 0, 100 }, // retrigger release
    { 71, 0, 0, 200 }, // pitch bend
    { 72, 0, 0, 5000 }, // attack bend
    { 73, 0, 0, 5000 }, // hold bend
    { 74, 0, 0, 5000 }, // decay bend
    { 75, 0, 0, 5000 }, // retrigger release bend
    { 76, 0, 0, 100 }, // intensity
    { 77, 0, 0, 600 }, // delay length
    { 78, 0, 0, 5000 }, // delay filter frequency
    { 79, 0, 70, 500 }, // delay filter resonance
    { 80, 0, 0, 100 }, // delay lowpass
    { 81, 0, 0, 100 }, // delay bandpass
    { 82, 0, 0, 100 }, // delay highpass
    { 83, 0, 0, 100 }, // dry mix
    { 84, 0, 0, 100 }, // delay mix
    { 85, 0, 0, 100 }, // reverb level
    { 86, 0, 0, 100 }, // crunch level
    { 87, 1, 0, 2 }, // crunch type
    { 88, 0, 0, 5000 }, // frequency
    { 89, 0, 70, 500 }, // resonance
    { 90, 0, 0, 100 }, // lowpass
    { 91, 0, 0, 100 }, // bandpass
    { 92, 0, 0, 100 }, // highpass
    { 93, 1, 0, 11 }, // LFO waveform
    { 94, 0, 0, 2000 }, // LFO frequency
    { 95, 0, 0, 100 }, // LFO amplitude
    { 96, 0, 0, 500 }, // filter LFO sensitivity
    { 97, 0, 0, 200 }, // output amplifier
    { 3, 0, 0, 100 }, // global gain
    { 33, 1, 0, 1 }, // barry harris mode
    { 39, 1, 0, 1 }, // chord layout
    { 34, 1, 0, 6 }, // chord frame shift
    { 21, 1, 0, 1 }, // retrigger chords
    { 202, 1, 0, 29 }, // alt layout maj
    { 203, 1, 0, 29 }, // alt layout min
    { 204, 1, 0, 29 }, // alt layout 7th
    { 205, 1, 0, 29 }, // alt layout maj+7th
    { 206, 1, 0, 29 }, // alt layout min+7th
    { 207, 1, 0, 29 }, // alt layout maj+min
    { 208, 1, 0, 29 }, // alt layout all three
    { 120, 1, 0, 5 }, // chord shuffling
    { 198, 1, 0, 4 }, // octave change
    { 199, 0, 0, 1500 }, // glide chords
    { 37, 1, 0, 3 }, // chord inversion
    { 38, 1, 0, 4 }, // chord spacing
    { 111, 1, 0, 2 }, // voice leading
    { 112, 1, 0, 24 }, // voice leading range
    { 23, 1, 0, 2 }, // slash level
    { 113, 1, 0, 4 }, // slash voice
    { 114, 1, 0, 1 }, // slash re-voice
    { 115, 1, 0, 5 }, // cantus
    { 265, 1, 0, 4 }, // chord voice
    { 270, 1, 0, 5 }, // first note voice
    { 271, 1, 0, 5 }, // second note voice
    { 272, 1, 0, 5 }, // third note voice
    { 273, 1, 0, 5 }, // fourth note voice
    { 274, 1, 0, 14 }, // rhythm style
    { 275, 1, 0, 2 }, // rhythm bass
    { 276, 1, 0, 2 }, // rhythm chords
    { 277, 1, 0, 2 }, // rhythm follows hands
    { 278, 1, 0, 2 }, // rhythm chord change
    { 279, 0, 10, 200 }, // rhythm articulation
    { 280, 0, 0, 100 }, // rhythm accents
    { 281, 1, 0, 1 }, // tap tempo counts
    { 282, 1, 0, 1 }, // MIDI chords
    { 121, 0, 0, 100 }, // amplitude 1
    { 122, 1, 0, 11 }, // waveform 1
    { 123, 0, 50, 200 }, // frequency multiplier 1
    { 124, 0, 0, 100 }, // amplitude 2
    { 125, 1, 0, 11 }, // waveform 2
    { 126, 0, 50, 200 }, // frequency multiplier 2
    { 127, 0, 0, 100 }, // amplitude 3
    { 128, 1, 0, 11 }, // waveform 3
    { 129, 0, 50, 200 }, // frequency multiplier 3
    { 130, 0, 0, 100 }, // noise
    { 131, 0, 0, 100 }, // first note
    { 132, 0, 0, 100 }, // second note
    { 133, 0, 0, 100 }, // third note
    { 134, 0, 0, 100 }, // fourth note
    { 135, 0, 0, 100 }, // inter-note delay
    { 136, 0, 0, 100 }, // random note delay
    { 137, 0, 0, 5000 }, // attack
    { 138, 0, 0, 5000 }, // hold
    { 139, 0, 0, 5000 }, // decay
    { 140, 0, 0, 100 }, // sustain
    { 141, 0, 0, 5000 }, // release
    { 142, 0, 0, 100 }, // retrigger release
    { 143, 0, 0, 5000 }, // base frequency
    { 144, 0, 0, 100 }, // keytrack value
    { 145, 0, 70, 500 }, // resonance
    { 146, 0, 0, 5000 }, // attack
    { 147, 0, 0, 5000 }, // hold
    { 148, 0, 0, 5000 }, // decay
    { 149, 0, 0, 100 }, // sustain
    { 150, 0, 0, 5000 }, // release
    { 151, 0, 0, 100 }, // retrigger release
    { 152, 1, 0, 11 }, // LFO waveform
    { 153, 0, 0, 2000 }, // LFO frequency
    { 154, 0, 0, 100 }, // LFO amplitude
    { 155, 0, 0, 500 }, // filter sensitivity
    { 118, 0, 0, 100 }, // formant vowel
    { 119, 0, 0, 100 }, // formant amount
    { 239, 0, 0, 100 }, // formant voice size
    { 240, 0, 0, 100 }, // formant resonance
    { 156, 1, 0, 11 }, // waveform
    { 157, 0, 0, 2000 }, // frequency
    { 158, 0, 0, 500 }, // keytrack value
    { 159, 0, 0, 100 }, // amplitude
    { 160, 1, 0, 11 }, // waveform
    { 161, 0, 0, 2000 }, // frequency
    { 162, 0, 0, 100 }, // keytrack value
    { 163, 0, 0, 100 }, // amplitude
    { 164, 0, 0, 5000 }, // attack
    { 165, 0, 0, 5000 }, // hold
    { 166, 0, 0, 5000 }, // decay
    { 167, 0, 0, 100 }, // sustain
    { 168, 0, 0, 5000 }, // release
    { 169, 0, 0, 100 }, // retrigger release
    { 170, 0, 0, 200 }, // pitch bend
    { 171, 0, 0, 5000 }, // attack bend 
    { 172, 0, 0, 5000 }, // hold bend
    { 173, 0, 0, 5000 }, // decay bend
    { 174, 0, 0, 100 }, // retrigger release bend
    { 175, 0, 0, 100 }, // intensity
    { 176, 0, 0, 600 }, // delay length
    { 177, 0, 0, 5000 }, // delay filter frequency
    { 178, 0, 70, 500 }, // delay filter resonance
    { 179, 0, 0, 100 }, // delay lowpass
    { 180, 0, 0, 100 }, // delay bandpass
    { 181, 0, 0, 100 }, // delay highpass
    { 182, 0, 0, 100 }, // dry mix
    { 183, 0, 0, 100 }, // delay mix
    { 184, 0, 0, 100 }, // reverb level
    { 185, 0, 0, 100 }, // crunch level
    { 186, 1, 0, 2 }, // crunch type
    { 187, 0, 30, 300 }, // default_bpm
    { 188, 1, 1, 16 }, // cycle length
    { 189, 1, 1, 8 }, // measure update
    { 190, 0, 50, 150 }, // shuffle value
    { 191, 0, 20, 1000 }, // note pushed duration
    { 220, 0, 0, 128 }, // rythm pattern
    { 221, 0, 0, 128 }, // rythm pattern
    { 222, 0, 0, 128 }, // rythm pattern
    { 223, 0, 0, 128 }, // rythm pattern
    { 224, 0, 0, 128 }, // rythm pattern
    { 225, 0, 0, 128 }, // rythm pattern
    { 226, 0, 0, 128 }, // rythm pattern
    { 227, 0, 0, 128 }, // rythm pattern
    { 228, 0, 0, 128 }, // rythm pattern
    { 229, 0, 0, 128 }, // rythm pattern
    { 230, 0, 0, 128 }, // rythm pattern
    { 231, 0, 0, 128 }, // rythm pattern
    { 232, 0, 0, 128 }, // rythm pattern
    { 233, 0, 0, 128 }, // rythm pattern
    { 234, 0, 0, 128 }, // rythm pattern
    { 235, 0, 0, 128 }, // rythm pattern
    { 192, 0, 0, 5000 }, // frequency
    { 193, 0, 70, 500 }, // resonance
    { 194, 0, 0, 100 }, // lowpass
    { 195, 0, 0, 100 }, // bandpass
    { 196, 0, 0, 100 }, // highpass
    { 197, 0, 0, 200 }, // output amplifier
};

// Which controls may move each address, from each parameter's "controls" in
// parameters.json: "all" (the default) for the knobs, hover and the double tap;
// "tap" for the double tap only, which sets an exact value, for settings a sweep
// would only scramble (a bitmask, the knob layer under the knob turning it, a MIDI
// mode); "none" for settings no control should touch (the controls' own wiring,
// the instrument's setup, MIDI routing). Addresses with no parameter are "none".
// It goes by the setting, not its address, so a new one can live anywhere.
#define PARAMETER_CONTROL_NONE 0
#define PARAMETER_CONTROL_TAP 1
#define PARAMETER_CONTROL_ALL 2
static const uint8_t parameter_control[512] = {
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 2, 2, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 2, 2, 0, 0,
    1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
    2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};

// Page 1's factory defaults, as stored (floats in hundredths), from each parameter's
// default_value: the same in every bank. Page 0's are the factory presets in main.cpp,
// tuned by hand; page 1 needs nothing added there by hand.
static const int16_t parameter_page1_defaults[256] = {
    0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 0, 7, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100, 100, 0, 0, 0, 0, 0, 50, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};

#endif // PARAMETER_LOOKUP_H
