// Generated by firmware/generator/temperaments.py. Edit that file, not this one.
//
// One row per temperament, in the order stored in presets (the temperament
// parameter). edo_index selects the division of the octave: 0 is twelve notes,
// 1 and 2 the 19 and 31 step tables in main.cpp. cents are offsets from equal
// temperament for pitch classes C, C#, D ... B, used only when edo_index is 0,
// with A at 0 so A sounds at the master tuning pitch.
#pragma once
#include <Arduino.h>

struct TemperamentProfile {
  uint8_t edo_index;
  int8_t cents[12];
};

const TemperamentProfile temperament_profiles[] = {
  {0, {  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0}},   // 0 equal
  {0, { 10, -14,   3,  21,  -3,  14, -10,   7, -17,   0,  17,  -7}},   // 1 quarter-comma meantone
  {0, { 16,  27,  20,  31,   2,  14,   6,  18,  29,   0,  12,   4}},   // 2 five-limit just (C major)
  {0, { -6,   8,  -2, -12,   2,  -8,   6,  -4,  10,   0, -10,   4}},   // 3 pythagorean
  {0, { 12,   2,   4,   6,   2,  10,   0,   8,   4,   0,   8,   4}},   // 4 werckmeister III
  {0, { 10,   0,   3,   4,  -3,   8,   0,   7,   2,   0,   6,  -1}},   // 5 kirnberger III
  {0, {  6,   0,   2,   4,  -2,   8,  -2,   4,   2,   0,   6,  -4}},   // 6 vallotti
  {0, {  6,  -4,   2,   0,  -2,   4,  -6,   4,  -2,   0,   2,  -4}},   // 7 young no. 2
  {0, {  8,  -2,   3,   2,  -3,   6,  -4,   5,   0,   0,   4,  -1}},   // 8 kellner
  {0, {  5,  -7,   2,  10,  -2,   7,  -5,   3,  -8,   0,   8,  -3}},   // 9 sixth-comma meantone
  {1, {  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0}},   // 10 19-EDO
  {2, {  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0}},   // 11 31-EDO
};
const uint8_t temperament_count = sizeof(temperament_profiles) / sizeof(temperament_profiles[0]);
