// Generated by firmware/generator/temperaments.py. Edit that file, not this one.
//
// One row per temperament, in the order stored in presets (address 237).
// edo_index selects the division of the octave: 0 is twelve notes, and
// indexes 1 and 2 are the 19 and 31 step tables in main.cpp. cents are
// offsets from equal temperament per pitch class C..B, used only when
// edo_index is 0.
#pragma once
#include <Arduino.h>

struct TemperamentProfile {
  uint8_t edo_index;
  int8_t cents[12];
};

const TemperamentProfile temperament_profiles[] = {
  {0, {  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0}},   // 0 equal
  {0, {  0, -24,  -7,  10, -14,   3, -21,  -3, -27, -10,   7, -17}},   // 1 quarter-comma meantone
  {0, {  0,  12,   4,  16, -14,  -2, -10,   2,  14, -16,  -4, -12}},   // 2 five-limit just (C major)
  {0, {  0, -10,   4,  -6,   8,  -2,  12,   2,  -8,   6,  -4,  10}},   // 3 pythagorean
  {1, {  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0}},   // 4 19-EDO
  {2, {  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0}},   // 5 31-EDO
  {0, {  0, -10,  -8,  -6, -10,  -2, -12,  -4,  -8, -12,  -4,  -8}},   // 6 werckmeister III
  {0, {  0, -10,  -7,  -6, -14,  -2, -10,  -3,  -8, -10,  -4, -12}},   // 7 kirnberger III
  {0, {  0,  -6,  -4,  -2,  -8,   2,  -8,  -2,  -4,  -6,   0, -10}},   // 8 vallotti
  {0, {  0, -10,  -4,  -6,  -8,  -2, -12,  -2,  -8,  -6,  -4, -10}},   // 9 young no. 2
  {0, {  0, -10,  -5,  -6, -11,  -2, -12,  -3,  -8,  -8,  -4,  -9}},   // 10 kellner
  {0, {  0, -11,  -3,   5,  -7,   2, -10,  -2, -13,  -5,   3,  -8}},   // 11 sixth-comma meantone
};
const uint8_t temperament_profile_count = sizeof(temperament_profiles) / sizeof(temperament_profiles[0]);
