// Generated by firmware/generator/temperaments.py. Edit that file, not this one.
//
// One row per temperament, in the order stored in presets (address 237).
// edo_index selects the division of the octave: 0 is twelve notes, and
// indexes 1 and 2 are the 19 and 31 step tables in main.cpp. cents are
// offsets from equal temperament per pitch class C..B, used only when
// edo_index is 0.
#pragma once
#include <Arduino.h>

struct TemperamentProfile {
  uint8_t edo_index;
  int8_t cents[12];
};

const TemperamentProfile temperament_profiles[] = {
  {0, {  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0}},   // 0 equal
  {0, {  0,  17,  -7,  10, -14,   3, -21,  -3,  14, -10,   7, -17}},   // 1 quarter-comma meantone
  {0, {  0,  12,   4,  16, -14,  -2, -10,   2,  14, -16,  -4, -12}},   // 2 five-limit just (C major)
  {0, {  0, -10,   4,  -6,   8,  -2,  12,   2,  -8,   6,  -4,  10}},   // 3 pythagorean
  {1, {  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0}},   // 4 19-EDO
  {2, {  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0}},   // 5 31-EDO
};
const uint8_t temperament_profile_count = sizeof(temperament_profiles) / sizeof(temperament_profiles[0]);
