#!/usr/bin/env python3
"""Temperament profiles for the minichord: the one place they are defined.

Each profile is one entry in PROFILES. Running this script writes:

  ../include/temperament_profiles.h   the table the firmware reads
  parameters.json                     the temperament parameter's max_value and tooltip

and prints the `options` and `optionNotes` lines for the temperament control in
Sound Lab's params.js, which lives in another repository.

Profile numbers are stored in presets, so a profile's position in PROFILES must
never change: add new profiles at the end only.

Twelve-note profiles are defined musically and turned into whole-cent offsets
from equal temperament, anchored on C:

  fifths(...)   twelve fifths round the circle, C-G, G-D, ... A#-F, F-C, each
                given as its deviation from a pure 3:2 in cents. One is None:
                it takes up whatever is needed for the circle to close (the
                wolf, in a meantone).
  ratios(...)   the twelve notes C, Db ... B as frequency ratios to C.

Divisions of the octave other than twelve use edo(n). Those need note tables in
main.cpp (the edo_* arrays), generated by gen_edo.py, so only divisions that
already have them (19 and 31) are accepted here.

Run:  python3 temperaments.py           regenerate
      python3 temperaments.py --check   exit 1 if anything generated is out of date
"""
import json, os, re, sys
from math import log2

PURE_FIFTH = 1200 * log2(3 / 2)
SYNTONIC_COMMA = 1200 * log2(81 / 80)
PYTHAGOREAN_COMMA = 1200 * log2(531441 / 524288)

# divisions main.cpp has note tables for, and their index into edo_steps[]
EDO_INDEX = {12: 0, 19: 1, 31: 2}


def fifths(deviations):
    assert len(deviations) == 12 and deviations.count(None) == 1, "twelve fifths, exactly one None"
    dev = list(deviations)
    # twelve fifths have to add up to seven octaves
    dev[dev.index(None)] = 7 * 1200 - 12 * PURE_FIFTH - sum(d for d in dev if d is not None)
    pitch = [0.0] * 12
    pos, pc = 0.0, 0
    for k in range(11):
        pos += PURE_FIFTH + dev[k]
        pc = (pc + 7) % 12
        pitch[pc] = pos % 1200
    return ("twelve", [round(pitch[i] - 100 * i) for i in range(12)])


def ratios(rs):
    assert len(rs) == 12 and rs[0] == 1, "twelve ratios starting from 1"
    return ("twelve", [round(1200 * log2(r) - 100 * i) for i, r in enumerate(rs)])


def edo(n):
    assert n in EDO_INDEX and n != 12, f"{n}-EDO has no note tables in main.cpp; generate them with gen_edo.py first"
    return ("edo", n)


# ---------------------------------------------------------------------------
# name:    in the parameters.json tooltip
# label:   the Sound Lab option
# note:    the Sound Lab explanation for the option
# tuning:  fifths(), ratios() or edo()
PROFILES = [
    dict(name="equal", label="Equal",
         note="Twelve identical steps. Every key sounds the same and no interval is quite in tune — a major third is 13.7 cents sharp, which is the faint beating you hear in a piano chord.",
         tuning=fifths([-PYTHAGOREAN_COMMA / 12] * 11 + [None])),
    dict(name="quarter-comma meantone", label="Meantone",
         note="Quarter-comma meantone, what most Renaissance and early Baroque music was written for. Major thirds are pure. Fifths pay for it, 5.4 cents flat, and keys far from C get progressively stranger — which is why that music stays near home.",
         # eleven fifths a quarter of a syntonic comma narrow; the wolf sits between F# and C#
         tuning=fifths([-SYNTONIC_COMMA / 4] * 6 + [None] + [-SYNTONIC_COMMA / 4] * 5)),
    dict(name="five-limit just (C major)", label="Just",
         note="Five-limit just intonation for C major. Thirds and fifths dead in tune in the home key, noticeably out in others.",
         tuning=ratios([1, 16/15, 9/8, 6/5, 5/4, 4/3, 45/32, 3/2, 8/5, 5/3, 16/9, 15/8])),
    dict(name="pythagorean", label="Pythagorean",
         note="Pure 3:2 fifths all the way round. Bright, wide thirds at 21.5 cents sharp. Right for medieval music, wrong for most of what came after.",
         tuning=fifths([0] * 6 + [None] + [0] * 5)),
    dict(name="19-EDO", label="19-EDO",
         note="Nineteen steps to the octave. The buttons mean exactly what they did, but C# and Db are now different notes a step apart, with C# the lower. Minor thirds land within a cent of pure; fifths pay 7 cents for it.",
         tuning=edo(19)),
    dict(name="31-EDO", label="31-EDO",
         note="Thirty-one steps. Major thirds essentially exact, and the augmented sixth lands within a cent of the 7:4 harmonic seventh — the interval twelve-note tuning has no room for. Sharps and flats are two steps apart here.",
         tuning=edo(31)),
    # Well temperaments and a second meantone, as a piano tuner would set them.
    # Every one is anchored on C and rounded to whole cents like the others.
    dict(name="werckmeister III", label="Werckmeister III",
         note="Andreas Werckmeister, 1691. Four fifths (C–G, G–D, D–A and B–F#) narrowed by a quarter of the Pythagorean comma, the rest pure. Every key is playable: C and F major have the calmest thirds, 3.9 cents wide, and Db, F# and Ab major the widest, 21.5.",
         tuning=fifths([-PYTHAGOREAN_COMMA / 4] * 3 + [0, 0, -PYTHAGOREAN_COMMA / 4] + [0] * 5 + [None])),
    dict(name="kirnberger III", label="Kirnberger III",
         note="Johann Philipp Kirnberger, 1779. The fifths from C to E are narrowed by a quarter of the syntonic comma, so C–E is a pure 5:4; F#–C# gives up a schisma and the rest are pure. The home keys are very sweet and the far ones pointedly bright.",
         # C-G, G-D, D-A, A-E a quarter syntonic comma narrow; F#-C# a schisma narrow
         tuning=fifths([-SYNTONIC_COMMA / 4] * 4 + [0, 0, -(PYTHAGOREAN_COMMA - SYNTONIC_COMMA)] + [0] * 4 + [None])),
    dict(name="vallotti", label="Vallotti",
         note="Francesco Antonio Vallotti, 18th century. The six fifths from F to B are narrowed by a sixth of the Pythagorean comma and the other six are pure. Smooth and even-handed, and a common choice today for Baroque music: thirds from 5.9 cents wide in F, C and G major to 21.5 in Db, F# and B.",
         # C-G through E-B tempered; F-C, the closing fifth, takes the sixth share
         tuning=fifths([-PYTHAGOREAN_COMMA / 6] * 5 + [0] * 6 + [None])),
    dict(name="young no. 2", label="Young",
         note="Thomas Young, 1800. Vallotti's shape moved up a fifth: the six fifths from C to F# are narrowed by a sixth of the Pythagorean comma, the rest pure. C, D and G major have the calmest thirds, 5.9 cents wide.",
         tuning=fifths([-PYTHAGOREAN_COMMA / 6] * 6 + [0] * 5 + [None])),
    dict(name="kellner", label="Kellner",
         note="Herbert Anton Kellner's 1977 proposal for the tuning of Bach's Well-Tempered Clavier. Five fifths (C–G, G–D, D–A, A–E and B–F#) narrowed by a fifth of the Pythagorean comma. Thirds from 2.7 cents wide in C major to 21.5 in Db, F# and Ab.",
         tuning=fifths([-PYTHAGOREAN_COMMA / 5] * 4 + [0, -PYTHAGOREAN_COMMA / 5] + [0] * 5 + [None])),
    dict(name="sixth-comma meantone", label="1/6 Meantone",
         note="Meantone with fifths narrowed by a sixth of the syntonic comma instead of a quarter. Major thirds are 7.2 cents wide rather than pure, and the wolf between G# and Eb shrinks to 16 cents, so more keys are usable. Often associated with Gottfried Silbermann's organs.",
         # eleven fifths a sixth syntonic comma narrow; the wolf sits between G# and Eb
         tuning=fifths([-SYNTONIC_COMMA / 6] * 8 + [None] + [-SYNTONIC_COMMA / 6] * 3)),
    # add new profiles here, at the end
]

TOOLTIP_TAIL = "Anchored on C, so keys far from C sound progressively stranger in the unequal ones, as they did historically"
TEMPERAMENT_ADDRESS = 237
# paths from this script, so it runs from any directory
HERE = os.path.dirname(os.path.abspath(__file__))
HEADER = os.path.join(HERE, "..", "include", "temperament_profiles.h")
PARAMETERS = os.path.join(HERE, "parameters.json")


def header_text():
    rows = []
    for i, p in enumerate(PROFILES):
        kind, value = p["tuning"]
        if kind == "twelve":
            assert all(-128 <= c <= 127 for c in value), f"{p['name']}: offsets must fit in int8_t"
            cents = ", ".join(f"{c:3d}" for c in value)
            rows.append(f"  {{0, {{{cents}}}}},   // {i} {p['name']}")
        else:
            rows.append(f"  {{{EDO_INDEX[value]}, {{{', '.join(['  0'] * 12)}}}}},   // {i} {p['name']}")
    return (
        "// Generated by firmware/generator/temperaments.py. Edit that file, not this one.\n"
        "//\n"
        "// One row per temperament, in the order stored in presets (address 237).\n"
        "// edo_index selects the division of the octave: 0 is twelve notes, and\n"
        "// indexes 1 and 2 are the 19 and 31 step tables in main.cpp. cents are\n"
        "// offsets from equal temperament per pitch class C..B, used only when\n"
        "// edo_index is 0.\n"
        "#pragma once\n"
        "#include <Arduino.h>\n"
        "\n"
        "struct TemperamentProfile {\n"
        "  uint8_t edo_index;\n"
        "  int8_t cents[12];\n"
        "};\n"
        "\n"
        "const TemperamentProfile temperament_profiles[] = {\n"
        + "\n".join(rows) + "\n"
        "};\n"
        "const uint8_t temperament_profile_count = sizeof(temperament_profiles) / sizeof(temperament_profiles[0]);\n"
    )


def tooltip_text():
    names = ", ".join(f"{i}={p['name']}" for i, p in enumerate(PROFILES))
    return f"tuning of the twelve notes: {names}. {TOOLTIP_TAIL}"


def parameters_text(current):
    line_re = re.compile(r'^(.*"sysex_adress":\s*%d\s*,.*)$' % TEMPERAMENT_ADDRESS, re.M)
    lines = line_re.findall(current)
    assert len(lines) == 1, f"expected one line with address {TEMPERAMENT_ADDRESS} in {PARAMETERS}"
    line = lines[0]
    new = re.sub(r'"max_value":\s*\d+', f'"max_value":{len(PROFILES) - 1}', line, count=1)
    new = re.sub(r'"tooltip":"(?:[^"\\]|\\.)*"', lambda m: '"tooltip":' + json.dumps(tooltip_text(), ensure_ascii=False), new, count=1)
    return current.replace(line, new)


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    check = "--check" in sys.argv
    stale = []
    header = header_text()
    try:
        old_header = open(HEADER, encoding="utf-8").read()
    except FileNotFoundError:
        old_header = None
    if old_header != header:
        stale.append(HEADER)
        if not check:
            open(HEADER, "w", encoding="utf-8").write(header)
    params = open(PARAMETERS, encoding="utf-8").read()
    new_params = parameters_text(params)
    json.loads(new_params)
    if new_params != params:
        stale.append(PARAMETERS)
        if not check:
            open(PARAMETERS, "w", encoding="utf-8").write(new_params)
    if check:
        if stale:
            print("out of date: " + ", ".join(stale) + " (run python3 temperaments.py)")
            sys.exit(1)
        print(f"temperaments: {len(PROFILES)} profiles, generated files up to date")
        return
    print(("updated: " + ", ".join(stale)) if stale else "already up to date")
    print(f"\nSound Lab params.js, temperament control (addr {TEMPERAMENT_ADDRESS}): max {len(PROFILES) - 1}, and")
    print("        options: " + json.dumps([p["label"] for p in PROFILES], ensure_ascii=False).replace('","', '", "') + ",")
    print("        optionNotes: [")
    for p in PROFILES:
        print("          " + json.dumps(p["note"], ensure_ascii=False) + ",")
    print("        ],")


if __name__ == "__main__":
    main()
